project:
  type: website

execute:
  freeze: auto

website:
  title: "Michal Mottl"
  site-url: "https://mottl.io"
  navbar:
    logo: images/MM.jpg
    logo-alt: "Michal Mottl"
    right:
      - href: index.qmd
        text: Home
      - href: services.qmd
        text: Work with me
      - href: about.qmd
        text: About
      - posts.qmd

format:
  html:
    theme: [default, theme.scss]
    toc: true
    include-after-body:
      - _includes/lang-toggle.html

